---
# tasks file for gbs.go

- name: install go on Fedora systems
  dnf:
    name: golang
    state: latest
  when: ansible_distribution == "Fedora"


- name: install go on Red Hat Enterprise Linux and CentOS systems
  yum:
    name: golang
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: install go on Debian and Ubuntu systems
  apt:
    name: golang
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
